version: "3.8"

services:
  db:
    container_name: api_db
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env.dev

  api:
    container_name: api
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/usr/src/api
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
