# Generated by Django 3.2.14 on 2022-07-13 19:05

from django.db import migrations
from django.apps.registry import Apps
import time


def generate_slug() -> str:
    """ Helper function to generate a dummy slug for those instances
    # created before slug field was added

    Returns:
        str: slug created using a timestamp
    """
    return f"dummy-product-slug-{round(time.time() * 100_000)}"


def populate_reference(apps: Apps, *_) -> None:
    """Function to be run when migration is applied

    Args:
        apps (Apps): historical models available
    """
    Product = apps.get_model('products', 'Product')
    for obj in Product.objects.all():
        obj.slug = generate_slug()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.RunPython(populate_reference)
    ]
