# Generated by Django 3.2.14 on 2022-07-13 20:00

from django.db import migrations, models
from django.utils.text import slugify
from django.apps.registry import Apps


def modify_product_name_and_slug(apps: Apps, *_) -> None:
    """initialy name was not unique. Since slug was added and it uses the name
    as base, we now requiere the name to be unique. This function modifies the
    product name and slug to make them uniques using their sku.

    Args:
        apps (Apps): historical models available
    """
    Product = apps.get_model('products', 'Product')
    for obj in Product.objects.all().order_by('-id'):
        if Product.objects.filter(name=obj.name).exclude(id=obj.id).exists():
            new_name = f"{obj.name} {obj.sku}"
            obj.name = new_name
            obj.slug = slugify(new_name)
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.RunPython(modify_product_name_and_slug),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=128, unique=True),
        ),
    ]
